Shivansh Added issue 11
Project-Books/books-api pull request #34
Opened 2020-12-29 08:09 UTC by shivansh29

## Summary of change

Derived query by genre 

## Related issue

Closes #11 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [ ] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [ ] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [ ] Ensure code changes pass all tests

- [ ] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [ ] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [ ] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [ ] Set this pull request to 'draft' if you are still working on it

- [ ] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

2021-01-03 09:05 UTC, knjk04 requested changes
Thanks for working on this. Please address the review comment

2021-01-03 09:05 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/repository/BookRepository.java
> +    Book findByTitle(@Param("booktitle") String title);
Could you please change this to not use JPQL? It should be

```java
Book findByTitle(String bookTitle);
```

2021-01-03 09:05 UTC, knjk04 commented
Also, please resolve the merge conflict

2021-01-10 09:23 UTC, knjk04 commented
How are you getting on with this?

2021-01-10 10:08 UTC, shivansh29 commented
Will Complete it in 2 days

2021-01-14 07:09 UTC, knjk04 commented
I noticed you committed. Is this ready for another review?

2021-01-14 11:02 UTC, shivansh29 commented
Yes

2021-01-16 08:22 UTC, knjk04 requested changes
Thanks for working on this.

Please see my review comments. Also, this doesn't compile for me (even after adding in the missing closing brace). One of the reasons is because a derived query cannot be made. The error message is quite descriptive, so I'll let you figure it out. If you need help, however, feel free to create a new discussion on GitHub or join our Slack channel.

2021-01-16 08:22 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/resolver/QueryResolver.java
> +
You're missing a closing brace here

2021-01-16 08:22 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/repository/BookRepository.java
> +    Book findByBooktitle( String booktitle);
This issue was meant to create a derived query to find books by genre, not title. Could you please change this?

2021-01-23 07:18 UTC, knjk04 commented
How are you getting on with this?

2021-01-23 10:29 UTC, shivansh29 commented
Please check I have merged it with new Changes

2021-01-24 07:24 UTC, knjk04 requested changes
Thanks. I've left some feedback as this is not quite right yet. Please ensure you get it to compile and work correctly (the missing closing brace was not still added).

This is not showing up on `localhost:8080/playground`. You will need to also add the query signature to our schema file in `src/main/resources/graphql/query.graphqls`. Please use the new signature where the argument is of type `Genre`, which corresponds to our enum, `genre.graphqls`.

> Ensure your commit messages are descriptive (i.e. a commit message should effectively summarise what change(s) you made)

The above is from our contributing document. Please note that your current commit messages do not summarise what you did. Could you please fix this (e.g. with an interactive rebase)?

2021-01-24 07:24 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/repository/BookRepository.java
> +    Book findByGenre( String genre);
There may be multiple books in a genre, so could you please change the return type to a `List<Book>`

2021-01-24 07:24 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/resolver/QueryResolver.java
> +
This is still missing

2021-01-24 07:24 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/repository/BookRepository.java
> +    Book findByGenre( String genre);
Also, we don't want to search by a `String`. Rather, we would like to pass in our enum, `BookGenre`.

2021-01-24 07:24 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/resolver/QueryResolver.java
> +    public Book findByGenre(String genre) {
Change argument type to our genre enum

2021-01-24 07:24 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/resolver/QueryResolver.java
> +
Could you please remove this extraneous line?

2021-01-26 15:48 UTC, shivansh29 commented
I'll  close this pull request  and create a new one    
I hope that's fine by you

2021-01-26 17:04 UTC, knjk04 commented
That's fine

2021-01-27 10:35 UTC, closed without merging