Title derived query 10
Project-Books/books-api pull request #48
Opened 2021-01-14 13:30 UTC by nikole24

## Summary of change

add a query for finding books by name and a test for this query

## Related issue

Closes #10 ]

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [ ] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [ ] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [ ] Ensure code changes pass all tests

- [ ] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [ ] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [ ] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [ ] Set this pull request to 'draft' if you are still working on it

- [ ] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

2021-01-15 15:18 UTC, nikole24 commented
Do I need to change something?

2021-01-16 09:08 UTC, knjk04 requested changes
Thanks for working on this! I've left some comments for you to address

2021-01-16 09:08 UTC, knjk04 commented on src/test/java/com/karankumar/booksapi/repository/BookRepositoryTest.java
> +
Could you please remove these extra two lines?

2021-01-16 09:08 UTC, knjk04 commented on src/test/java/com/karankumar/booksapi/repository/BookRepositoryTest.java
> +        return book;
Instead of creating a variable and then returning, could you please return it immediately?

2021-01-16 09:08 UTC, knjk04 commented on src/test/java/com/karankumar/booksapi/repository/BookRepositoryTest.java
> +    }
As per our style guide, could you please have one blank line between the end of one method and the start of the next?

2021-01-16 09:08 UTC, knjk04 commented on src/test/java/com/karankumar/booksapi/repository/BookRepositoryTest.java
>      }
As per our style guide, could you please have one blank line between the end of one method and the start of the next?

Also, could you please ensure `@Test` is correctly indented (in line with `@DisplayName`)?

2021-01-16 09:08 UTC, knjk04 commented on src/main/java/com/karankumar/booksapi/repository/BookRepository.java
> +   @Query("SELECT b FROM Book b where upper(b.title) = upper(?1)")
Could you please remove this line? Instead, could you please rename the method to `findByTitleIgnoreCase`?

2021-01-18 19:32 UTC, knjk04 approved these changes
Thanks for working on this! I've made a few small changes

2021-01-18 19:33 UTC, merged